# Site settings
title: Sazed
description: Sazed's description
url: "http://raystudioco.github.io" # the base hostname & protocol for your site
copyright: Copyright &copy; Abhay Rana
email: ray@raystudiophoto.com
repo: raystudioco/sazed
categories:
  top: Main Articles
  policy: Policy
# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
